"""
Similar Problem 1: Find the Difference
Difficulty: Easy
Pattern: Bit Manipulation (XOR)

Problem:
You are given two strings s and t. String t is generated by randomly shuffling string s
and then adding one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
- 0 <= s.length <= 1000
- t.length == s.length + 1
- s and t consist of lowercase English letters
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        Approach: XOR all characters

        Strategy:
        1. XOR all characters in both strings
        2. Duplicates cancel out (a ^ a = 0)
        3. Only the extra character remains
        4. Same principle as single number problem
        """

        #

        #

        #

        #

        #

        #

        #

        #

        #

        #

        #

        #

        #

        #

        #

        #

        result = 0

        # XOR all characters in s
        for char in s:
            result ^= ord(char)

        # XOR all characters in t
        for char in t:
            result ^= ord(char)

        return chr(result)


# Alternative: Using sum
class SolutionSum:
    def findTheDifference(self, s: str, t: str) -> str:
        return chr(sum(ord(c) for c in t) - sum(ord(c) for c in s))


# Test cases
if __name__ == "__main__":
    solution = Solution()

    # Test case 1
    assert solution.findTheDifference("abcd", "abcde") == "e"
    print("✓ Test case 1 passed")

    # Test case 2
    assert solution.findTheDifference("", "y") == "y"
    print("✓ Test case 2 passed")

    # Test case 3
    assert solution.findTheDifference("a", "aa") == "a"
    print("✓ Test case 3 passed")

    print("\nAll test cases passed!")
