/*
 * Ported from: 12-bit-manipulation/analogue-questions/Python/single-number-similar1.py
 * --- Original description ---
Similar Problem 1: Find the Difference
Difficulty: Easy
Pattern: Bit Manipulation (XOR)

Problem:
You are given two strings s and t. String t is generated by randomly shuffling string s
and then adding one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
- 0 <= s.length <= 1000
- t.length == s.length + 1
- s and t consist of lowercase English letters
 */

import java.util.*;
import java.util.function.*;


public class SingleNumberSimilar1Java {



    static class Solution {
        public String findTheDifference(String s, String t) {
            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            //

            // result = 0
            // for char in s:
            // result ^= ord(char)
            // for char in t:
            // result ^= ord(char)
            // return chr(result)

            throw new UnsupportedOperationException("Implement findTheDifference");
        }

    }

    public static void main(String[] args) {
        Solution sol = new Solution();
        assert (sol.findTheDifference("abcd", "abcde") == "e");
        System.out.println("✓ Test case 1 passed");
        assert (sol.findTheDifference("", "y") == "y");
        System.out.println("✓ Test case 2 passed");
        assert (sol.findTheDifference("a", "aa") == "a");
        System.out.println("✓ Test case 3 passed");
        System.out.println("\nAll test cases passed!");
    }
}
